import type { Metadata } from "next";
import { Karla} from "next/font/google";
import "./globals.css";
import { satoshi } from "@/fonts/font";

const geistKarla = Karla({
  subsets: ["latin"],
  variable: "--font-geist-karla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/icons/logo.svg",
  }
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistKarla.variable} ${satoshi.variable} font-karla antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
